language: python
python:
    - "2.7"
env:
  matrix:
  - BROWSER=firefox
  - BROWSER=edge
  - BROWSER=chrome
  - BROWSER=opera
install: true
script:
    - cd tools/
    - ./make_release.py -b ${BROWSER}